web3j:
  chains:
    HECO: http://node.wallet-dp.huobiapps.com/heco-rpc
    ETH: http://54.64.51.164:8545
    BSC: https://data-seed-prebsc-1-s1.binance.org:8545/
    OEC: http://node.wallet-dp.huobiapps.com/oec-rpc
    POLYGON: https://rpc-mainnet.matic.network
    AVAX: https://api.avax.network/ext/bc/C/rpc

server:
  port: 8081


spring:
  profiles.active: dev
  main.allow-bean-definition-overriding: true
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB
  application:
    name: monitor-contract
    logging:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&connectTimeout=15000&socketTimeout=30000&failOverReadOnly=false
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      isAutoCommit: false
      connectionTimeout: 10000
      maxPoolSize: 2
      minIdle: 1
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    database: 0
    host: localhost
    port: 6379


mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml  # mapper映射文件
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    db-config:
      #table-prefix: "t_"
      id-type: auto
      table-underline: true
      #column-format: "f_%s"
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl