web3j:
  chains:
    HECO: http://node.wallet-dp.huobiapps.com/heco-rpc
    ETH: http://54.64.51.164:8545
    BSC: https://data-seed-prebsc-1-s1.binance.org:8545/
    OEC: http://node.wallet-dp.huobiapps.com/oec-rpc
    POLYGON: https://rpc-mainnet.matic.network
    AVAX: https://api.avax.network/ext/bc/C/rpc

server:
  port: 8081


spring:
  profiles.active: dev
  main.allow-bean-definition-overriding: true
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB
  application:
    name: monitor-contract
    logging:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      keep-alive: true
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
        wall.config:
          multi-statement-allow: true
          none-base-statement-allow: true
      filters: stat
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        profile-enable: true
  redis:
    cluster:
      nodes:
        - localhost:6399
    database: 0
    password: t7cCSe_V3x65tbSR
    pool:
      maxTotal: 10
      maxWaitMillis: 2000
      minIdle: 2
    port: 6379
    timeout: 30000ms

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml  # mapper映射文件
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    db-config:
      #table-prefix: "t_"
      id-type: auto
      table-underline: true
      #column-format: "f_%s"
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl